database:
  server: DESKTOP-CN12MMO\MYSQLWORKSPACE
  db: AdventureWorks2019
  user:
  pwd:

weathermap:
  latitude: 43.675
  longitude: -79.3474
  part: include
  apikey: 2050e8e8eed8513bea5353a0a7325f73

