database:
  server: DESKTOP-CN12MMO\MYSQLWORKSPACE
  db: AdventureWorks2019
  user:
  pwd:

weathermap:
  latitude: 43.675
  longitude: -79.3474
  part: hourly
  apikey: 74b98793aadc3d5f77bdc4e31391c2dc

omdb:
  apikey: b17ec89c

